stages:
  export_data:
    cmd: python scripts/export_data.py --output-dir data/raw
    deps:
      - scripts/export_data.py
    outs:
      - data/raw/screenings.csv
      - data/raw/chat_logs.jsonl
  
  preprocess:
    cmd: python scripts/preprocess.py
    deps:
      - scripts/preprocess.py
      - data/raw/screenings.csv
    outs:
      - data/processed/train_phq9.csv
      - data/processed/test_phq9.csv
      - data/processed/train_gad7.csv
      - data/processed/test_gad7.csv
  
  train_screening:
    cmd: python scripts/train_screening.py
    deps:
      - scripts/train_screening.py
      - data/processed/train_phq9.csv
      - data/processed/train_gad7.csv
    params:
      - train.learning_rate
      - train.n_estimators
      - train.max_depth
    metrics:
      - metrics/train_metrics.json:
          cache: false
    outs:
      - models/screening_phq9.pkl
      - models/screening_gad7.pkl
  
  evaluate:
    cmd: python scripts/evaluate.py
    deps:
      - scripts/evaluate.py
      - models/screening_phq9.pkl
      - models/screening_gad7.pkl
      - data/processed/test_phq9.csv
      - data/processed/test_gad7.csv
    metrics:
      - metrics/eval_metrics.json:
          cache: false
