const mongoose = require('mongoose');

const recommendationFeedbackSchema = new mongoose.Schema({
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    resourceId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Resource',
        required: true
    },
    recommendationId: {
        type: String, // generated by ML service
        required: true
    },
    action: {
        type: String,
        enum: ['viewed', 'clicked', 'saved', 'rated', 'dismissed'],
        required: true
    },
    rating: {
        type: Number,
        min: 1,
        max: 5
    },
    timeSpent: {
        type: Number, // seconds
        default: 0
    },
    context: {
        type: String, // where recommendation was shown (dashboard, chat, etc.)
        default: 'dashboard'
    },
    timestamp: {
        type: Date,
        default: Date.now
    }
});

// Index for quick analytics
recommendationFeedbackSchema.index({ userId: 1, resourceId: 1 });
recommendationFeedbackSchema.index({ action: 1 });

const RecommendationFeedback = mongoose.model('RecommendationFeedback', recommendationFeedbackSchema);

module.exports = RecommendationFeedback;
